// Code generated by hand to stand in for controller-gen's deepcopy-gen.
//
// Normally this file is produced by running:
//
//	controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/..."
//
// which requires the k8s.io/code-generator toolchain. That tool wasn't
// available in the sandbox this project was originally scaffolded in (no
// network access to fetch it), so these methods are written out manually
// here instead. They implement exactly what controller-gen would produce:
// a deep copy for every field, and DeepCopyObject() to satisfy
// k8s.io/apimachinery's runtime.Object interface, which every CRD type
// registered with a scheme must implement.
//
// If you add fields to IPSpaceClaimSpec or IPSpaceClaimStatus, update the
// corresponding DeepCopyInto method below to match — or, better, install
// controller-gen (`go install sigs.k8s.io/controller-gen/cmd/controller-gen@latest`)
// and regenerate this file properly:
//
//	controller-gen object paths="./api/v1alpha1/..."

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all fields of IPSpaceClaimSpec into out.
func (in *IPSpaceClaimSpec) DeepCopyInto(out *IPSpaceClaimSpec) {
	*out = *in
	if in.CIDRSize != nil {
		out.CIDRSize = new(int32)
		*out.CIDRSize = *in.CIDRSize
	}
	if in.Tags != nil {
		out.Tags = make(map[string]string, len(in.Tags))
		for k, v := range in.Tags {
			out.Tags[k] = v
		}
	}
}

// DeepCopy returns a deep copy of IPSpaceClaimSpec.
func (in *IPSpaceClaimSpec) DeepCopy() *IPSpaceClaimSpec {
	if in == nil {
		return nil
	}
	out := new(IPSpaceClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of IPSpaceClaimStatus into out.
func (in *IPSpaceClaimStatus) DeepCopyInto(out *IPSpaceClaimStatus) {
	*out = *in
	if in.LastDriftCheckTime != nil {
		out.LastDriftCheckTime = in.LastDriftCheckTime.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy of IPSpaceClaimStatus.
func (in *IPSpaceClaimStatus) DeepCopy() *IPSpaceClaimStatus {
	if in == nil {
		return nil
	}
	out := new(IPSpaceClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of IPSpaceClaim into out.
func (in *IPSpaceClaim) DeepCopyInto(out *IPSpaceClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of IPSpaceClaim.
func (in *IPSpaceClaim) DeepCopy() *IPSpaceClaim {
	if in == nil {
		return nil
	}
	out := new(IPSpaceClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object, required for every type
// registered with a Kubernetes scheme (client-go, controller-runtime, etc.
// all rely on this to safely clone objects out of caches/informers).
func (in *IPSpaceClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields of IPSpaceClaimList into out.
func (in *IPSpaceClaimList) DeepCopyInto(out *IPSpaceClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]IPSpaceClaim, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy of IPSpaceClaimList.
func (in *IPSpaceClaimList) DeepCopy() *IPSpaceClaimList {
	if in == nil {
		return nil
	}
	out := new(IPSpaceClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object for IPSpaceClaimList.
func (in *IPSpaceClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
